services:
  resume-builder-db:
    image: postgres:latest
    container_name: resume-builder-container
    restart: always
    environment:
      - POSTGRES_USER=resumeBuilderUser
      - POSTGRES_PASSWORD=resume
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
